/* Creación de usuario si estás trabajando con BD Oracle XE */
ALTER SESSION SET "_Oracle_Script"=TRUE;

CREATE USER PRY2205_S7 
IDENTIFIED BY "PRY2205.semana_7" 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO PRY2205_S7;

GRANT RESOURCE, CREATE VIEW, CREATE SYNONYM, CREATE PUBLIC SYNONYM TO PRY2205_S7;

ALTER USER PRY2205_S7 DEFAULT ROLE RESOURCE;

