
/*“La instrucción ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE se utiliza en Oracle XE para permitir la creación de 
usuarios locales sin prefijo C##, debido a la arquitectura CDB introducida desde Oracle 12c.”*/
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


--Creacion de usuarios

--Owner
create user PRY2205_EFT 
identified by "Pry2205_eft."
default tablespace users
quota 10M on user
temporary tablespace temp;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW,
      CREATE SEQUENCE,CREATE SYNONYM
TO PRY2205_EFT;


--Desarrollador
create user PRY2205_EFT_DES
identified by "Pry2205_eft.des"
default tablespace users
quota 10m on users
temporary tablespace temp;



create user PRY2205_EFT_CON
identified by "Pry2205_eft.con"
default tablespace users
quota 10m on users
temporary tablespace temp;


--Creacion de roles

create role PRY2205_ROL_D;

create role PRY2205_ROL_C;

--Rol desarrollador
GRANT CREATE SESSION, CREATE VIEW TO PRY2205_ROL_D;

--Rol consulta
GRANT CREATE SESSION TO PRY2205_ROL_C;

-- Rol DESARROLLADOR (solo lectura)
GRANT SELECT ON PRY2205_EFT.CLIENTE TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.CONTRATO TO PRY2205_ROL_D;

-- AGREGA SOLO LAS TABLAS NECESARIAS

-- Rol CONSULTA
GRANT SELECT ON PRY2205_EFT.CLIENTE TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.CONTRATO TO PRY2205_ROL_C;



--Asignacion de roles

GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;


-- Sinónimos públicos para CASO 2
CREATE PUBLIC SYNONYM PROFESIONAL     FOR PRY2205_EFT.PROFESIONAL;
CREATE PUBLIC SYNONYM PROFESION       FOR PRY2205_EFT.PROFESION;
CREATE PUBLIC SYNONYM ISAPRE          FOR PRY2205_EFT.ISAPRE;
CREATE PUBLIC SYNONYM TIPO_CONTRATO   FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE PUBLIC SYNONYM RANGOS_SUELDOS  FOR PRY2205_EFT.RANGOS_SUELDOS;
CREATE PUBLIC SYNONYM CARTOLA_PROFESIONALES 
FOR PRY2205_EFT.CARTOLA_PROFESIONALES;

GRANT SELECT ON PRY2205_EFT.PROFESIONAL     TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.PROFESION       TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.ISAPRE          TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO   TO PRY2205_EFT_DES;
GRANT SELECT ON PRY2205_EFT.RANGOS_SUELDOS  TO PRY2205_EFT_DES;

GRANT INSERT ON PRY2205_EFT.CARTOLA_PROFESIONALES 
TO PRY2205_EFT_DES;








